In [10]:
import numpy as np

a=np.matrix('1,2;3,4')
b=np.matrix('1,1;0,2')
c=np.identity(2,dtype=int)
print(a)
print(b)
print(c)

e=np.linalg.inv(a)
print(e)
print(e*a)

f=np.transpose(a)
print(f)

[[1 2]
 [3 4]]
[[1 1]
 [0 2]]
[[1 0]
 [0 1]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]
[[1 3]
 [2 4]]
